services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: stridetrack-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend-venv:/app/.venv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: stridetrack-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - backend

volumes:
  backend-venv:
  frontend-node-modules:


networks:
  default:
    name: supabase_network_StrideTrack
    external: true
