/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * StrideTrack API
 * OpenAPI spec version: 0.1.0
 */

export interface ExampleRunResponse {
  id: string;
  athlete_name: string;
  distance_meters: number;
  duration_seconds: number;
  avg_ground_contact_time_ms: number | null;
  created_at: string;
}
