/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * StrideTrack API
 * OpenAPI spec version: 0.1.0
 */

export interface ExampleRunUpdate {
  athlete_name?: string | null;
  distance_meters?: number | null;
  duration_seconds?: number | null;
  avg_ground_contact_time_ms?: number | null;
}
