import { ChartCard } from "@/components/charts/shared/ChartCard";
import { QueryError } from "@/components/ui/QueryError";
import { QueryLoading } from "@/components/ui/QueryLoading";
import { useGetRunFeedback } from "@/hooks/useRunFeedback.hooks";
import type { ChartProps } from "@/types/chart.types";

const TITLE = "AI Coach Feedback";
const DESCRIPTION =
  "This summary is generated by a large language model (LLM) based on aggregate run metrics. It is intended as a quick coaching prompt — not a substitute for expert analysis. Results may vary.";

export const RunFeedbackCard = ({ runId }: ChartProps) => {
  const {
    runFeedback,
    runFeedbackIsLoading,
    runFeedbackError,
    runFeedbackRefetch,
  } = useGetRunFeedback(runId);

  if (runFeedbackIsLoading)
    return (
      <ChartCard title={TITLE} description={DESCRIPTION}>
        <QueryLoading />
      </ChartCard>
    );
  if (runFeedbackError)
    return (
      <ChartCard title={TITLE} description={DESCRIPTION}>
        <QueryError
          error={runFeedbackError}
          refetch={() => void runFeedbackRefetch()}
        />
      </ChartCard>
    );
  if (!runFeedback) return null;

  return (
    <ChartCard title={TITLE} description={DESCRIPTION}>
      <p className="text-sm text-foreground leading-relaxed">{runFeedback}</p>
    </ChartCard>
  );
};
