///Colors for recharts charts
export const chartColors = {
  card: "hsl(var(--card))",
  primary: "hsl(var(--primary))",
  secondary: "hsl(var(--secondary))",
  destructive: "hsl(var(--destructive))",
  destructiveHover: "hsl(var(--destructive-hover))",
  primaryHover: "hsl(var(--primary-hover))",
  mutedForeground: "hsl(var(--muted-foreground))",
  mutedForegroundHover: "hsl(var(--muted-foreground-hover))",
  border: "hsl(var(--border))",
  foreground: "hsl(var(--foreground))",
  primaryLight: "hsl(var(--primary) / 0.2)",
  leftFoot: "#f97316",
  rightFoot: "hsl(var(--foreground))",
  phaseApproach: "#000000",
  phaseAntepenultimate: "#facc15",
  phasePenultimate: "#ef4444",
  phaseTakeoff: "#22c55e",
  phaseHop: "#3b82f6",
  phaseStep: "#8b5cf6",
  phaseJump: "#10b981",
} as const;
